using System;
using ThatCore.Config.Toml;
using ThatCore.Config.Toml.Writers;
using DropThat.Drop.CharacterDropSystem.Managers;
using ThatCore.Config.Toml.Schema;
using DropThat.Debugging;
using DropThat.Drop.CharacterDropSystem.Configuration;

namespace DropThat.Drop.CharacterDropSystem.Debug;

internal static class TemplateWriter
{
    public static void WriteLoadedConfigsToDisk()
    {
        var templates = CharacterDropTemplateManager.GetTemplates();

        var tomlFile = ConfigurationFileManager.Mapper.MapToConfigFromTemplates(templates);

        var content = TomlConfigWriter.WriteToString(tomlFile, new TomlWriterSettings()
        {
            FileName = "drop_that.character_drop_loaded_configs.cfg",
            AddComments = false,
            Header =
                $"# This file was auto-generated by Drop That {DropThatPlugin.Version} at {DateTimeOffset.UtcNow.ToString("u")}, with Valheim '{Version.CurrentVersion.m_major}.{Version.CurrentVersion.m_minor}.{Version.CurrentVersion.m_patch}'.\n" +
                $"# The entries listed here were generated from the internally loaded CharacterDrop configurations.\n" +
                $"# This is intended to reveal the state of Drop That, after loading configs from all sources, and before applying them to their respective target drop tables.\n" +
                $"# This file is not scanned by Drop That, and any changes done will therefore have no effect. Copy sections into a CharacterDrop config in the configs folder if you want to change things."
        });

        DebugFileWriter.WriteFile(content, "drop_that.character_drop_loaded_configs.cfg", "loaded CharacterDrop configs");
    }

    public static void WriteSchemaToDisk()
    {
        var content = TomlSchemaWriter.WriteToString(
            ConfigurationFileManager.Schema, 
            new TomlWriterSettings()
            {
                FileName = "drop_that.character_drop_schema.cfg",
                AddComments = true,
                Header =
                    $"# This file was auto-generated by Drop That {DropThatPlugin.Version} at {DateTimeOffset.UtcNow.ToString("u")}, with Valheim '{Version.CurrentVersion.m_major}.{Version.CurrentVersion.m_minor}.{Version.CurrentVersion.m_patch}'.\n" +
                    $"# This file is a description of all available settings for drop_that.character_drop configs, their default values and the expected structure.\n" +
                    $"# For more detailed documentation, see the Drop That wiki."
            });

        DebugFileWriter.WriteFile(content, "drop_that.character_drop_schema.cfg", "schema for CharacterDrop configs");

        var listContent = TomlSchemaWriter.WriteToString(
            ConfigurationFileManager.ListSchema,
            new TomlWriterSettings()
            {
                FileName = "drop_that.character_drop_schema_list.cfg",
                AddComments = true,
                Header =
                $"# This file was auto-generated by Drop That {DropThatPlugin.Version} at {DateTimeOffset.UtcNow.ToString("u")}, with Valheim '{Version.CurrentVersion.m_major}.{Version.CurrentVersion.m_minor}.{Version.CurrentVersion.m_patch}'.\n" +
                    $"# This file is a description of all available settings for drop_that.character_drop_list configs, their default values and the expected structure.\n" +
                    $"# For more detailed documentation, see the Drop That wiki."
            });

        DebugFileWriter.WriteFile(listContent, "drop_that.character_drop_schema_list.cfg", "schema for CharacterDrop list configs");
    }
}
